name: xbatcher-ML-1-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - numpy
  - xarray
  - intake
  - matplotlib
  - IPython
  - tensorflow
  - xbatcher
  - intake-xarray
  - gcsfs
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - pydata-sphinx-theme
  - jsonschema-with-format-nongpl
  - docutils
  - sphinx-pythia-theme
